import { createWriteStream } from 'node:fs'
import { mkdir } from 'node:fs/promises'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { randomUUID } from 'node:crypto'
import PDFDocument from 'pdfkit'
import type { PlatformDraft } from '../workflow/states.js'
import type { TenantContext } from '../types/tenant.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const UPLOADS_DIR = join(__dirname, '../../uploads')

interface DraftPdfMeta {
  topicTitle?: string
  seedPrompt?: string
}

function writePdfToFile(doc: PDFKit.PDFDocument, filePath: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const stream = createWriteStream(filePath)
    doc.pipe(stream)
    doc.end()
    stream.on('finish', () => resolve())
    stream.on('error', reject)
  })
}

function addSection(
  doc: PDFKit.PDFDocument,
  title: string,
  body: string,
  accent: string,
): void {
  doc.moveDown(0.5)
  doc.fontSize(13).fillColor(accent).text(title, { continued: false })
  doc.moveDown(0.25)
  doc.fontSize(11).fillColor('#333333').text(body, {
    align: 'left',
    lineGap: 4,
  })
}

export async function generateDraftPdf(
  draft: PlatformDraft,
  tenant: TenantContext,
  meta: DraftPdfMeta = {},
): Promise<{ filePath: string; fileName: string }> {
  await mkdir(join(UPLOADS_DIR, tenant.userId), { recursive: true })

  const fileName = `${tenant.userId}/draft-${randomUUID()}.pdf`
  const filePath = join(UPLOADS_DIR, fileName)
  const doc = new PDFDocument({ margin: 50, size: 'A4' })

  doc.fontSize(22).fillColor('#111111').text('Content Preview', { align: 'center' })
  doc.moveDown(0.5)

  if (meta.topicTitle) {
    doc.fontSize(14).fillColor('#555555').text(meta.topicTitle, { align: 'center' })
    doc.moveDown(0.25)
  }

  if (meta.seedPrompt) {
    doc.fontSize(10).fillColor('#888888').text(`Theme: ${meta.seedPrompt}`, { align: 'center' })
  }

  doc.moveDown(1)
  doc
    .strokeColor('#dddddd')
    .lineWidth(1)
    .moveTo(50, doc.y)
    .lineTo(doc.page.width - 50, doc.y)
    .stroke()
  doc.moveDown(0.5)

  addSection(doc, 'Facebook', draft.facebook, '#1877F2')
  addSection(doc, 'Instagram', draft.instagram, '#E1306C')
  addSection(doc, 'LinkedIn', draft.linkedin, '#0A66C2')
  addSection(doc, 'Image Prompt', draft.imagePrompt, '#666666')

  doc.moveDown(1)
  doc.fontSize(9).fillColor('#aaaaaa').text('Generated by SocialPostAgent', { align: 'center' })

  await writePdfToFile(doc, filePath)
  return { filePath, fileName }
}

export function getDraftPdfPublicUrl(fileName: string, tenant: TenantContext): string | undefined {
  if (!tenant.publicBaseUrl) return undefined
  return `${tenant.publicBaseUrl}/uploads/${fileName}`
}
